federation_version: 2
subgraphs:
  user-service:
    routing_url: http://localhost:3000/graphql
    schema:
      subgraph_url: http://localhost:3000/graphql
  bookshelf:
    routing_url: http://localhost:3002/graphql
    schema:
      subgraph_url: http://localhost:3002/graphql